version: '3'

services:
  bot:
    image: bot_image
    container_name: bot
    build:
      context: ./bot
      dockerfile: Dockerfile
    ports:
      - "1313:1313"

  db:
    image: db_image
    container_name: db
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      POSTGRES_DB: bot_tg
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256\nhost replication all 0.0.0.0/0 md5"
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    ports:
      - "5433:5432"
    command: |
      postgres
      -c wal_level=replica
      -c hot_standby=on
      -c max_wal_senders=10
      -c max_replication_slots=10
      -c hot_standby_feedback=on
    env_file:
      - 'ENV.env'

  db_repl:
    image: db_repl_image
    container_name: db_repl
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    user: postgres
    command: |
      bash -c "
      until pg_basebackup --pgdata=/var/lib/postgresql/data -R --slot=replication_slot --host=$DB_HOST --port=5432
      do
      echo 'Waiting for primary connect...'
      sleep 1s
      done
      echo 'Backup done, starting replica...'
      chmod 0700 /var/lib/postgresql/data
      postgrespostgres -c 'host replication postgres $DB_HOST/32 md5'    
      "
    env_file:
      - 'ENV.env'
